// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package trimm_designsystem.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DS_GenerateDefaultDesignSystemRecords extends UserAction<java.lang.Void>
{
	public DS_GenerateDefaultDesignSystemRecords(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = getContext();

		// --- DS_DesignToken records (Colors, Borders, Radius, and Shadows) ---
		Object[][] tokens = new Object[][] {
				// Brand Colors (from _themes.scss)
				{ "--brand-1", "#00172b", "Color", "Primary brand color (Navy Blue)", "swatch-brand-1", null, null,
						null, null, null, 1 },
				{ "--brand-2", "#f37123", "Color", "Secondary brand color (Orange)", "swatch-brand-2", null, null, null,
						null, null, 2 },
				{ "--brand-3", "#0e808a", "Color", "Tertiary brand color (Teal)", "swatch-brand-3", null, null, null,
						null, null, 3 },

				// Base Colors
				{ "--base-black", "#231f20", "Color", "Base black color", "swatch-base-black", null, null, null, null,
						null, 4 },
				{ "--base-white", "#ffffff", "Color", "Base white color", "swatch-base-white", null, null, null, null,
						null, 5 },

				// Secondary Colors
				{ "--secondary-1", "#6e6f72", "Color", "Secondary color (Dark Grey)", "swatch-secondary-1", null, null,
						null, null, null, 6 },
				{ "--secondary-2", "#edd7c4", "Color", "Secondary color (Beige)", "swatch-secondary-2", null, null,
						null, null, null, 7 },

				// Support Colors
				{ "--support-1", "#392b78", "Color", "Support color (Purple)", "swatch-support-1", null, null, null,
						null, null, 8 },
				{ "--support-2", "#b92025", "Color", "Support color (Red - Error/Danger)", "swatch-support-2", null,
						null, null, null, null, 9 },
				{ "--support-3", "#176e4e", "Color", "Support color (Green - Success)", "swatch-support-3", null, null,
						null, null, null, 10 },
				{ "--support-4", "#ffc107", "Color", "Support color (Yellow - Warning)", "swatch-support-4", null, null,
						null, null, null, 11 },

				// Border (from _border.scss)
				{ "$border-0", "0", "Border", "No border", null, null, null, "border-style-0", null, null, 12 },
				{ "$border-1", "1px", "Border", "Thin border", null, null, null, "border-style-1", null, null, 13 },
				{ "$border-2", "2px", "Border", "Medium border", null, null, null, "border-style-2", null, null, 14 },
				{ "$border-4", "4px", "Border", "Thick border", null, null, null, "border-style-4", null, null, 15 },
				{ "$border-8", "8px", "Border", "Extra thick border", null, null, null, "border-style-8", null, null,
						16 },

				// Radius (from _radius.scss)
				{ "$radius-0", "0px", "Radius", "No border radius", null, null, "radius-style-0", null, null, null,
						17 },
				{ "$radius-4", "4px", "Radius", "Small border radius", null, null, "radius-style-4", null, null, null,
						18 },
				{ "$radius-8", "8px", "Radius", "Medium border radius", null, null, "radius-style-8", null, null, null,
						19 },
				{ "$radius-16", "16px", "Radius", "Large border radius", null, null, "radius-style-16", null, null,
						null, 20 },
				{ "$radius-full", "999px", "Radius", "Full border radius (circular)", null, null, "radius-style-full",
						null, null, null, 21 },

				// Shadow (from _shadow.scss)
				{ "$shadow-0", "none", "Shadow", "No shadow", null, "shadow-style-0", null, null, null, null, 22 },
				{ "$shadow-2", "0 2px 4px rgba(27, 28, 29, 0.05)", "Shadow", "Light shadow", null, "shadow-style-2",
						null, null, null, null, 23 },
				{ "$shadow-3", "0 4px 8px rgba(27, 28, 29, 0.10)", "Shadow", "Small shadow", null, "shadow-style-3",
						null, null, null, null, 24 },
				{ "$shadow-6", "0 6px 12px rgba(27, 28, 29, 0.12)", "Shadow", "Medium shadow", null, "shadow-style-6",
						null, null, null, null, 25 },
				{ "$shadow-8", "0 8px 16px rgba(27, 28, 29, 0.15)", "Shadow", "Large shadow", null, "shadow-style-8",
						null, null, null, null, 26 },
				{ "$shadow-12", "0 12px 24px rgba(27, 28, 29, 0.20)", "Shadow", "Extra large shadow", null,
						"shadow-style-12", null, null, null, null, 27 },

				// Spacing (from _spacing.scss)
				{ "$spacing-0", "0px", "Spacing", "No spacing", null, null, null, null, "spacing-style-0", null, 28 },
				{ "$spacing-4", "4px", "Spacing", "Extra small spacing", null, null, null, null, "spacing-style-4",
						null, 29 },
				{ "$spacing-8", "8px", "Spacing", "Small spacing", null, null, null, null, "spacing-style-8", null,
						30 },
				{ "$spacing-12", "12px", "Spacing", "Medium-small spacing", null, null, null, null, "spacing-style-12",
						null, 31 },
				{ "$spacing-16", "16px", "Spacing", "Medium spacing", null, null, null, null, "spacing-style-16", null,
						32 },
				{ "$spacing-24", "24px", "Spacing", "Large spacing", null, null, null, null, "spacing-style-24", null,
						33 },
				{ "$spacing-32", "32px", "Spacing", "Extra large spacing", null, null, null, null, "spacing-style-32",
						null, 34 },
				{ "$spacing-40", "40px", "Spacing", "Very large spacing", null, null, null, null, "spacing-style-40",
						null, 35 },
				{ "$spacing-64", "64px", "Spacing", "Huge spacing", null, null, null, null, "spacing-style-64", null,
						36 },
				{ "$spacing-auto", "auto", "Spacing", "Auto spacing", null, null, null, null, "spacing-style-auto",
						null, 37 },

				// Typography - Font Sizes (from _typography.scss)
				{ "$font-size-h1", "32px", "Typography", "Heading 1 font size", null, null, null, null, null,
						"font-size-h1-swatch", 38 },
				{ "$font-size-h2", "28px", "Typography", "Heading 2 font size", null, null, null, null, null,
						"font-size-h2-swatch", 39 },
				{ "$font-size-h3", "24px", "Typography", "Heading 3 font size", null, null, null, null, null,
						"font-size-h3-swatch", 40 },
				{ "$font-size-h4", "20px", "Typography", "Heading 4 font size", null, null, null, null, null,
						"font-size-h4-swatch", 41 },
				{ "$font-size-h5", "18px", "Typography", "Heading 5 font size", null, null, null, null, null,
						"font-size-h5-swatch", 42 },
				{ "$font-size-h6", "16px", "Typography", "Heading 6 font size", null, null, null, null, null,
						"font-size-h6-swatch", 43 },
				{ "$font-size-body-1", "18px", "Typography", "Body 1 font size", null, null, null, null, null,
						"font-size-body-1-swatch", 44 },
				{ "$font-size-body-2", "16px", "Typography", "Body 2 font size", null, null, null, null, null,
						"font-size-body-2-swatch", 45 },
				{ "$font-size-body-3", "14px", "Typography", "Body 3 font size", null, null, null, null, null,
						"font-size-body-3-swatch", 46 },
				{ "$font-size-body-4", "12px", "Typography", "Body 4 font size", null, null, null, null, null,
						"font-size-body-4-swatch", 47 },

				// Typography - Font Weights
				{ "$font-weight-light", "300", "Typography", "Light font weight", null, null, null, null, null,
						"font-weight-light-swatch", 48 },
				{ "$font-weight-regular", "400", "Typography", "Regular font weight", null, null, null, null, null,
						"font-weight-regular-swatch", 49 },
				{ "$font-weight-medium", "500", "Typography", "Medium font weight", null, null, null, null, null,
						"font-weight-medium-swatch", 50 },
				{ "$font-weight-semibold", "600", "Typography", "Semibold font weight", null, null, null, null, null,
						"font-weight-semibold-swatch", 51 },
				{ "$font-weight-bold", "700", "Typography", "Bold font weight", null, null, null, null, null,
						"font-weight-bold-swatch", 52 },

				// Typography - Line Heights
				{ "$line-height-h1", "1.2", "Typography", "Heading 1 line height", null, null, null, null, null,
						"line-height-h1-swatch", 53 },
				{ "$line-height-h2", "1.25", "Typography", "Heading 2 line height", null, null, null, null, null,
						"line-height-h2-swatch", 54 },
				{ "$line-height-h3", "1.3", "Typography", "Heading 3 line height", null, null, null, null, null,
						"line-height-h3-swatch", 55 },
				{ "$line-height-h4", "1.35", "Typography", "Heading 4 line height", null, null, null, null, null,
						"line-height-h4-swatch", 56 },
				{ "$line-height-h5", "1.4", "Typography", "Heading 5 line height", null, null, null, null, null,
						"line-height-h5-swatch", 57 },
				{ "$line-height-h6", "1.45", "Typography", "Heading 6 line height", null, null, null, null, null,
						"line-height-h6-swatch", 58 },
				{ "$line-height-body-1", "1.5", "Typography", "Body 1 line height", null, null, null, null, null,
						"line-height-body-1-swatch", 59 },
				{ "$line-height-body-2", "1.5", "Typography", "Body 2 line height", null, null, null, null, null,
						"line-height-body-2-swatch", 60 },
				{ "$line-height-body-3", "1.4", "Typography", "Body 3 line height", null, null, null, null, null,
						"line-height-body-3-swatch", 61 },
				{ "$line-height-body-4", "1.3", "Typography", "Body 4 line height", null, null, null, null, null,
						"line-height-body-4-swatch", 62 }
		};

		for (Object[] t : tokens) {
			IMendixObject token = Core.instantiate(context, "TRIMM_DesignSystem.DS_DesignToken");
			token.setValue(context, "TokenName", t[0]);
			token.setValue(context, "TokenValue", t[1]);
			token.setValue(context, "Category", t[2]);
			token.setValue(context, "Description", t[3]);
			token.setValue(context, "ColorStyle", t[4]);
			token.setValue(context, "ShadowStyle", t[5]);
			token.setValue(context, "RadiusStyle", t[6]);
			token.setValue(context, "BorderStyle", t[7]);
			token.setValue(context, "SpacingStyle", t[8]);
			token.setValue(context, "TypographyStyle", t[9]);
			token.setValue(context, "SortOrder", t[10]);
			Core.commit(context, token);
		}

		// --- DS_Component records (Restyled Components) ---
		Object[][] components = new Object[][] {
				// Accordion Component
				{ "Accordion", "Accordion", "RestyledMendix", "Navigation", "Stable",
						"Restyled Atlas accordion widget with TRIMM design tokens and brand colors", "1.0", true },

				// Alert Component
				{ "Alert", "Alert", "RestyledMendix", "Feedback", "Stable",
						"Restyled Atlas alert widget with TRIMM color variants and typography", "1.0", true },

				// Button Component
				{ "Button", "Button", "RestyledMendix", "Interactive", "Stable",
						"Restyled Atlas button widget with TRIMM variants, sizes, and brand styling", "1.0", true },

				// Checkbox Component
				{ "Checkbox", "Checkbox", "RestyledMendix", "Form", "Stable",
						"Restyled Atlas checkbox widget with TRIMM design system styling", "1.0", true },

				// Label Component
				{ "Label", "Label", "RestyledMendix", "Display", "Stable",
						"Restyled Atlas label widget with TRIMM color variants and sizing options", "1.0", true },

				// Menu Component
				{ "Menu", "Menu", "RestyledMendix", "Navigation", "Stable",
						"Restyled Atlas menu widget with TRIMM brand colors and navigation styling", "1.0", true },

				// Radio Component
				{ "Radio", "Radio", "RestyledMendix", "Form", "Stable",
						"Restyled Atlas radio button widget with TRIMM design tokens and styling", "1.0", true },

				// Sidebar Component
				{ "Sidebar", "Sidebar", "RestyledMendix", "Navigation", "Stable",
						"Restyled Atlas sidebar navigation with TRIMM brand colors and layout", "1.0", true },

				// Switch Component
				{ "Switch", "Switch", "RestyledMendix", "Form", "Stable",
						"Restyled Atlas switch/toggle widget with TRIMM design system styling", "1.0", true },

				// Tab Component
				{ "Tab", "Tab", "RestyledMendix", "Navigation", "Stable",
						"Restyled Atlas tab container widget with TRIMM styling and interactions", "1.0", true },

				// Textarea Component
				{ "Textarea", "Textarea", "RestyledMendix", "Form", "Stable",
						"Restyled Atlas textarea widget with TRIMM design tokens and form styling", "1.0", true },

				// Textbox Component
				{ "Textbox", "Textbox", "RestyledMendix", "Form", "Stable",
						"Restyled Atlas textbox widget with TRIMM design tokens and form styling", "1.0", true },

				// Tooltip Component
				{ "Tooltip", "Tooltip", "RestyledMendix", "Display", "Stable",
						"Restyled Atlas tooltip widget with TRIMM design and contextual styling", "1.0", true },

				// Topbar Component
				{ "Topbar", "Topbar", "RestyledMendix", "Navigation", "Stable",
						"Restyled Atlas topbar navigation with TRIMM brand colors and layout", "1.0", true },

				// Custom Components
				// Color Token Editor Component
				{ "ColorTokenEditor", "Color Token Editor", "Custom", "Development", "Stable",
						"Custom color token editor widget with TRIMM design system integration", "1.0", true },

				// Datepicker Component
				{ "Datepicker", "Datepicker", "Custom", "Form", "Stable",
						"Custom datepicker widget with TRIMM design tokens and calendar styling", "1.0", true },

				// Dropdown Component
				{ "Dropdown", "Dropdown", "Custom", "Interactive", "Stable",
						"Custom dropdown widget with TRIMM brand colors and menu styling", "1.0", true },

				// Range Datepicker Component
				{ "RangeDatepicker", "Range Datepicker", "Custom", "Form", "Stable",
						"Custom range datepicker widget with TRIMM design system and date range selection", "1.0",
						true }
		};

		// Store component identifiers for association linking
		java.util.Map<String, trimm_designsystem.proxies.DS_Component> componentByName = new java.util.HashMap<>();

		for (Object[] c : components) {
			IMendixObject component = Core.instantiate(context, "TRIMM_DesignSystem.DS_Component");
			component.setValue(context, "Name", c[0]);
			component.setValue(context, "DisplayName", c[1]);
			component.setValue(context, "ComponentType", c[2]);
			component.setValue(context, "Category", c[3]);
			component.setValue(context, "Status", c[4]);
			component.setValue(context, "Description", c[5]);
			component.setValue(context, "Version", c[6]);
			component.setValue(context, "IsActive", c[7]);
			Core.commit(context, component);
			componentByName.put((String) c[0], trimm_designsystem.proxies.DS_Component.initialize(context, component));
		}

		// --- DS_ComponentClass records (Component Classes for all components) ---
		Object[][] componentClasses = new Object[][] {
				// Button Component Classes (associate to "Button")
				{ "button-base", "Base button styling with TRIMM design tokens", 1, "Button" },
				{ "btn-default", "Default button variant with transparent background", 2, "Button" },
				{ "btn-cta", "Call-to-action button with orange background", 3, "Button" },
				{ "btn-inverse", "Inverse button variant with inverted colors", 4, "Button" },
				{ "btn-primary", "Primary button variant with navy blue background", 5, "Button" },
				{ "btn-info", "Info button variant with teal background", 6, "Button" },
				{ "btn-success", "Success button variant with green background", 7, "Button" },
				{ "btn-warning", "Warning button variant with yellow background", 8, "Button" },
				{ "btn-danger", "Danger button variant with red background", 9, "Button" },
				{ "btn-sm", "Small button size variant", 10, "Button" },
				{ "btn-md", "Medium button size variant", 11, "Button" },
				{ "btn-lg", "Large button size variant", 12, "Button" },
				{ "btn-icon-right", "Button with icon on the right side", 13, "Button" },
				{ "btn-icon-left", "Button with icon on the left side", 14, "Button" },

				// Accordion Component Classes (associate to "Accordion")
				{ "accordion-base", "Base accordion wrapper with TRIMM styling", 15, "Accordion" },

				// Alert Component Classes (associate to "Alert")
				{ "alert-base", "Base alert styling with TRIMM design tokens", 16, "Alert" },
				{ "alert-success", "Success alert variant with green background", 17, "Alert" },
				{ "alert-danger", "Danger alert variant with red background", 18, "Alert" },
				{ "alert-warning", "Warning alert variant with yellow background", 19, "Alert" },
				{ "alert-info", "Info alert variant with teal background", 20, "Alert" },

				// Checkbox Component Classes (associate to "Checkbox")
				{ "checkbox-base", "Base checkbox styling with TRIMM design tokens", 21, "Checkbox" },
				{ "checkbox-sm", "Small checkbox size variant", 22, "Checkbox" },
				{ "checkbox-md", "Medium checkbox size variant", 23, "Checkbox" },
				{ "checkbox-lg", "Large checkbox size variant", 24, "Checkbox" },

				// Label Component Classes (associate to "Label")
				{ "label-base", "Base label styling with TRIMM design tokens", 25, "Label" },
				{ "label-default", "Default label variant with teal background", 26, "Label" },
				{ "label-secondary", "Secondary label variant with orange background", 27, "Label" },
				{ "label-success", "Success label variant with green background", 28, "Label" },
				{ "label-danger", "Danger label variant with red background", 29, "Label" },
				{ "label-warning", "Warning label variant with yellow background", 30, "Label" },
				{ "label-sm", "Small label size variant", 31, "Label" },
				{ "label-md", "Medium label size variant", 32, "Label" },
				{ "label-lg", "Large label size variant", 33, "Label" },

				// Menu Component Classes (associate to "Menu")
				{ "menu-base", "Base menu styling with TRIMM design tokens", 34, "Menu" }
		};

		for (Object[] cc : componentClasses) {
			IMendixObject componentClass = Core.instantiate(context, "TRIMM_DesignSystem.DS_ComponentClass");
			componentClass.setValue(context, "ClassName", cc[0]);
			componentClass.setValue(context, "Description", cc[1]);
			componentClass.setValue(context, "SortOrder", cc[2]);
			// Link to DS_Component when provided (e.g., all Button classes)
			String linkToComponentName = (String) cc[3];
			if (linkToComponentName != null) {
				trimm_designsystem.proxies.DS_Component compProxy = componentByName.get(linkToComponentName);
				if (compProxy != null) {
					trimm_designsystem.proxies.DS_ComponentClass classProxy = trimm_designsystem.proxies.DS_ComponentClass
							.initialize(context, componentClass);
					classProxy.setDS_ComponentClass_DS_Component(context, compProxy);
					// Component not found; leave association empty
				} else {
					// Component not found; leave association empty
				}
			}
			Core.commit(context, componentClass);
		}

		// Safety pass: explicitly link all Button classes to the Button component
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> buttonCompList = com.mendix.core.Core
				.createXPathQuery("//TRIMM_DesignSystem.DS_Component[Name='Button']").execute(context);
		if (!buttonCompList.isEmpty()) {
			com.mendix.systemwideinterfaces.core.IMendixObject buttonCompObj = buttonCompList.get(0);
			trimm_designsystem.proxies.DS_Component buttonComp = trimm_designsystem.proxies.DS_Component
					.initialize(context, buttonCompObj);
			String[] buttonClassNames = { "button-base", "btn-default", "btn-cta", "btn-inverse", "btn-primary",
					"btn-info", "btn-success", "btn-warning", "btn-danger", "btn-sm", "btn-md", "btn-lg",
					"btn-icon-right", "btn-icon-left" };
			for (String className : buttonClassNames) {
				java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> classList = com.mendix.core.Core
						.createXPathQuery("//TRIMM_DesignSystem.DS_ComponentClass[ClassName='" + className + "']")
						.execute(context);
				if (!classList.isEmpty()) {
					trimm_designsystem.proxies.DS_ComponentClass classProxy = trimm_designsystem.proxies.DS_ComponentClass
							.initialize(context, classList.get(0));
					classProxy.setDS_ComponentClass_DS_Component(context, buttonComp);
					Core.commit(context, classProxy.getMendixObject());
				}
			}
		}

		// Safety pass: explicitly link all Accordion classes to the Accordion component
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> accordionCompList = com.mendix.core.Core
				.createXPathQuery("//TRIMM_DesignSystem.DS_Component[Name='Accordion']").execute(context);
		if (!accordionCompList.isEmpty()) {
			com.mendix.systemwideinterfaces.core.IMendixObject accordionCompObj = accordionCompList.get(0);
			trimm_designsystem.proxies.DS_Component accordionComp = trimm_designsystem.proxies.DS_Component
					.initialize(context, accordionCompObj);
			String[] accordionClassNames = { "accordion-base" };
			for (String className : accordionClassNames) {
				java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> classList = com.mendix.core.Core
						.createXPathQuery("//TRIMM_DesignSystem.DS_ComponentClass[ClassName='" + className + "']")
						.execute(context);
				if (!classList.isEmpty()) {
					trimm_designsystem.proxies.DS_ComponentClass classProxy = trimm_designsystem.proxies.DS_ComponentClass
							.initialize(context, classList.get(0));
					classProxy.setDS_ComponentClass_DS_Component(context, accordionComp);
					Core.commit(context, classProxy.getMendixObject());
				}
			}
		}

		// Safety pass: explicitly link all Alert classes to the Alert component
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> alertCompList = com.mendix.core.Core
				.createXPathQuery("//TRIMM_DesignSystem.DS_Component[Name='Alert']").execute(context);
		if (!alertCompList.isEmpty()) {
			com.mendix.systemwideinterfaces.core.IMendixObject alertCompObj = alertCompList.get(0);
			trimm_designsystem.proxies.DS_Component alertComp = trimm_designsystem.proxies.DS_Component
					.initialize(context, alertCompObj);
			String[] alertClassNames = { "alert-base", "alert-success", "alert-danger", "alert-warning", "alert-info" };
			for (String className : alertClassNames) {
				java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> classList = com.mendix.core.Core
						.createXPathQuery("//TRIMM_DesignSystem.DS_ComponentClass[ClassName='" + className + "']")
						.execute(context);
				if (!classList.isEmpty()) {
					trimm_designsystem.proxies.DS_ComponentClass classProxy = trimm_designsystem.proxies.DS_ComponentClass
							.initialize(context, classList.get(0));
					classProxy.setDS_ComponentClass_DS_Component(context, alertComp);
					Core.commit(context, classProxy.getMendixObject());
				}
			}
		}

		// Safety pass: explicitly link all Checkbox classes to the Checkbox component
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> checkboxCompList = com.mendix.core.Core
				.createXPathQuery("//TRIMM_DesignSystem.DS_Component[Name='Checkbox']").execute(context);
		if (!checkboxCompList.isEmpty()) {
			com.mendix.systemwideinterfaces.core.IMendixObject checkboxCompObj = checkboxCompList.get(0);
			trimm_designsystem.proxies.DS_Component checkboxComp = trimm_designsystem.proxies.DS_Component
					.initialize(context, checkboxCompObj);
			String[] checkboxClassNames = { "checkbox-base", "checkbox-sm", "checkbox-md", "checkbox-lg" };
			for (String className : checkboxClassNames) {
				java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> classList = com.mendix.core.Core
						.createXPathQuery("//TRIMM_DesignSystem.DS_ComponentClass[ClassName='" + className + "']")
						.execute(context);
				if (!classList.isEmpty()) {
					trimm_designsystem.proxies.DS_ComponentClass classProxy = trimm_designsystem.proxies.DS_ComponentClass
							.initialize(context, classList.get(0));
					classProxy.setDS_ComponentClass_DS_Component(context, checkboxComp);
					Core.commit(context, classProxy.getMendixObject());
				}
			}
		}

		// Safety pass: explicitly link all Label classes to the Label component
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> labelCompList = com.mendix.core.Core
				.createXPathQuery("//TRIMM_DesignSystem.DS_Component[Name='Label']").execute(context);
		if (!labelCompList.isEmpty()) {
			com.mendix.systemwideinterfaces.core.IMendixObject labelCompObj = labelCompList.get(0);
			trimm_designsystem.proxies.DS_Component labelComp = trimm_designsystem.proxies.DS_Component
					.initialize(context, labelCompObj);
			String[] labelClassNames = { "label-base", "label-default", "label-secondary", "label-success",
					"label-danger", "label-warning", "label-sm", "label-md", "label-lg" };
			for (String className : labelClassNames) {
				java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> classList = com.mendix.core.Core
						.createXPathQuery("//TRIMM_DesignSystem.DS_ComponentClass[ClassName='" + className + "']")
						.execute(context);
				if (!classList.isEmpty()) {
					trimm_designsystem.proxies.DS_ComponentClass classProxy = trimm_designsystem.proxies.DS_ComponentClass
							.initialize(context, classList.get(0));
					classProxy.setDS_ComponentClass_DS_Component(context, labelComp);
					Core.commit(context, classProxy.getMendixObject());
				}
			}
		}

		// Safety pass: explicitly link all Menu classes to the Menu component
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> menuCompList = com.mendix.core.Core
				.createXPathQuery("//TRIMM_DesignSystem.DS_Component[Name='Menu']").execute(context);
		if (!menuCompList.isEmpty()) {
			com.mendix.systemwideinterfaces.core.IMendixObject menuCompObj = menuCompList.get(0);
			trimm_designsystem.proxies.DS_Component menuComp = trimm_designsystem.proxies.DS_Component
					.initialize(context, menuCompObj);
			String[] menuClassNames = { "menu-base" };
			for (String className : menuClassNames) {
				java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> classList = com.mendix.core.Core
						.createXPathQuery("//TRIMM_DesignSystem.DS_ComponentClass[ClassName='" + className + "']")
						.execute(context);
				if (!classList.isEmpty()) {
					trimm_designsystem.proxies.DS_ComponentClass classProxy = trimm_designsystem.proxies.DS_ComponentClass
							.initialize(context, classList.get(0));
					classProxy.setDS_ComponentClass_DS_Component(context, menuComp);
					Core.commit(context, classProxy.getMendixObject());
				}
			}
		}

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DS_GenerateDefaultDesignSystemRecords";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
