// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package trimm_designsystem.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DS_GenerateDefaultDesignSystemRecords extends UserAction<java.lang.Void> {
	public DS_GenerateDefaultDesignSystemRecords(IContext context) {
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception {
		// BEGIN USER CODE
		IContext context = getContext();

		// --- DS_DesignToken records (Colors, Borders, and Radius) ---
		Object[][] tokens = new Object[][] {
				// Brand Colors (from _themes.scss)
				{ "--brand-1", "#00172b", "Color", "Primary brand color (Navy Blue)", "swatch-brand-1", null, null,
						null, null, null, null, null, 1 },
				{ "--brand-2", "#f37123", "Color", "Secondary brand color (Orange)", "swatch-brand-2", null, null, null,
						null, null, null, null, 2 },
				{ "--brand-3", "#0e808a", "Color", "Tertiary brand color (Teal)", "swatch-brand-3", null, null, null,
						null, null, null, null, 3 },

				// Base Colors
				{ "--base-black", "#231f20", "Color", "Base black color", "swatch-base-black", null, null, null, null,
						null, null, null, 4 },
				{ "--base-white", "#ffffff", "Color", "Base white color", "swatch-base-white", null, null, null, null,
						null, null, null, 5 },

				// Secondary Colors
				{ "--secondary-1", "#6e6f72", "Color", "Secondary color (Dark Grey)", "swatch-secondary-1", null, null,
						null, null, null, null, null, 6 },
				{ "--secondary-2", "#edd7c4", "Color", "Secondary color (Beige)", "swatch-secondary-2", null, null,
						null, null, null, null, null, 7 },

				// Support Colors
				{ "--support-1", "#392b78", "Color", "Support color (Purple)", "swatch-support-1", null, null, null,
						null, null, null, null, 8 },
				{ "--support-2", "#b92025", "Color", "Support color (Red - Error/Danger)", "swatch-support-2", null,
						null, null, null, null, null, null, 9 },
				{ "--support-3", "#176e4e", "Color", "Support color (Green - Success)", "swatch-support-3", null, null,
						null, null, null, null, null, 10 },
				{ "--support-4", "#ffc107", "Color", "Support color (Yellow - Warning)", "swatch-support-4", null, null,
						null, null, null, null, null, 11 },

				// Border (from _border.scss)
				{ "$border-0", "0", "Border", "No border", null, null, null, "0", "border-style-0", null, null, null,
						12 },
				{ "$border-1", "1px", "Border", "Thin border", null, null, null, "1px", "border-style-1", null, null,
						null, 13 },
				{ "$border-2", "2px", "Border", "Medium border", null, null, null, "2px", "border-style-2", null, null,
						null, 14 },
				{ "$border-4", "4px", "Border", "Thick border", null, null, null, "4px", "border-style-4", null, null,
						null, 15 },
				{ "$border-8", "8px", "Border", "Extra thick border", null, null, null, "8px", "border-style-8", null,
						null, null, 16 },

				// Radius (from _radius.scss)
				{ "$radius-0", "0px", "Radius", "No border radius", null, null, "0px", null, null, null, null,
						"radius-style-0", 17 },
				{ "$radius-4", "4px", "Radius", "Small border radius", null, null, "4px", null, null, null, null,
						"radius-style-4", 18 },
				{ "$radius-8", "8px", "Radius", "Medium border radius", null, null, "8px", null, null, null, null,
						"radius-style-8", 19 },
				{ "$radius-16", "16px", "Radius", "Large border radius", null, null, "16px", null, null, null, null,
						"radius-style-16", 20 },
				{ "$radius-full", "999px", "Radius", "Full border radius (circular)", null, null, "999px", null, null,
						null, null, "radius-style-full", 21 }
		};

		for (Object[] t : tokens) {
			IMendixObject token = Core.instantiate(context, "TRIMM_DesignSystem.DS_DesignToken");
			token.setValue(context, "TokenName", t[0]);
			token.setValue(context, "TokenValue", t[1]);
			token.setValue(context, "Category", t[2]);
			token.setValue(context, "Description", t[3]);
			token.setValue(context, "ColorStyle", t[4]);
			token.setValue(context, "ShadowStyle", t[5]);
			token.setValue(context, "RadiusStyle", t[6]);
			token.setValue(context, "BorderStyle", t[7]);
			token.setValue(context, "BorderStyleClass", t[8]);
			token.setValue(context, "SpacingStyle", t[9]);
			token.setValue(context, "SpacingStyleClass", t[10]);
			token.setValue(context, "TypographyStyle", t[11]);
			token.setValue(context, "RadiusStyleClass", t[12]);
			token.setValue(context, "ShadowStyleClass", t[13]);
			token.setValue(context, "SortOrder", t[14]);
			Core.commit(context, token);
		}

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * 
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString() {
		return "DS_GenerateDefaultDesignSystemRecords";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
