// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} csv
 * @param {string} dateToToggle
 * @returns {Promise.<string>}
 */
export async function ToggleDateInCsv(csv, dateToToggle) {
    // BEGIN USER CODE
    // Split CSV into array, clean whitespace, remove empty strings
    const currentDates = (csv || "")
        .split(",")
        .map(s => s.trim())
        .filter(Boolean);

    // Toggle logic: add if not present, remove if present
    const idx = currentDates.indexOf(dateToToggle);
    if (idx > -1) {
        currentDates.splice(idx, 1); // Remove
    } else {
        currentDates.push(dateToToggle); // Add
    }
    // Return new CSV string
    return currentDates.join(",");

    // END USER CODE
}
