// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} textToCopy
 * @returns {Promise.<void>}
 */
export async function CopyToClipboard(textToCopy) {
	// BEGIN USER CODE
	// Primary approach: Use modern Clipboard API (supported in most modern browsers)
	// This is the preferred method as it's more secure and user-friendly
	if (navigator && navigator.clipboard && navigator.clipboard.writeText) {
		await navigator.clipboard.writeText(textToCopy);
		return;
	} else {
		// Fallback approach: Use legacy document.execCommand for older browsers
		// This method requires creating a temporary DOM element to hold the text

		// Create a temporary textarea element to hold the text content
		var textarea = document.createElement("textarea");
		textarea.value = textToCopy;

		// Add the textarea to the DOM temporarily (required for execCommand to work)
		// The element must be visible and selectable for the copy operation
		document.body.appendChild(textarea);

		// Select all text content in the textarea
		textarea.select();

		try {
			// Execute the copy command using the legacy API
			// This will copy the selected text to the system clipboard
			document.execCommand('copy');
		} catch (err) {
			// Silently handle errors (e.g., user denied clipboard access, security restrictions)
			// In production, you might want to log these errors for debugging purposes
		}

		// Clean up: remove the temporary textarea from the DOM
		// This prevents memory leaks and keeps the DOM clean
		document.body.removeChild(textarea);
		return;
	}
	// END USER CODE
}
