// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Copies text to the system clipboard using the modern Clipboard API
 * with fallback support for older browsers using document.execCommand
 * 
 * @param {string} textToCopy - The text string to copy to clipboard
 * @returns {Promise.<void>} - Resolves when copy operation completes
 */
export async function CopyToClipboard(textToCopy) {
	// BEGIN USER CODE
	// Try modern Clipboard API first (supported in most modern browsers)
	if (navigator && navigator.clipboard && navigator.clipboard.writeText) {
		await navigator.clipboard.writeText(textToCopy);
		return;
	} else {
		// Fallback for older browsers using document.execCommand
		// Create a temporary textarea element to hold the text
		var textarea = document.createElement("textarea");
		textarea.value = textToCopy;
		// Add to DOM temporarily (required for execCommand to work)
		document.body.appendChild(textarea);
		// Select the text content
		textarea.select();
		try {
			// Execute the copy command
			document.execCommand('copy');
		} catch (err) {
			// Silently handle errors (e.g., user denied clipboard access)
			// Optionally handle error logging here if needed
		}
		// Clean up: remove the temporary textarea from DOM
		document.body.removeChild(textarea);
		return;
	}
	// END USER CODE
}
