// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// Initialize theme on page load by checking localStorage for saved preference
// This ensures the correct theme is applied immediately when the page loads
document.addEventListener("DOMContentLoaded", function () {
	const theme = localStorage.getItem("theme");
	if (theme === "dark") {
		document.documentElement.setAttribute("data-theme", "dark");
	}
});
// END EXTRA CODE

/**
 * Toggles between light and dark themes by updating the document's data-theme attribute
 * and persisting the user's preference in localStorage for future visits
 * 
 * @returns {Promise.<void>} - Resolves when theme toggle completes
 */
export async function ToggleTheme() {
	// BEGIN USER CODE
	// Get the current theme from the document's data-theme attribute
	const html = document.documentElement;
	const current = html.getAttribute("data-theme");

	// Toggle between light and dark themes
	if (current === "dark") {
		// Switch from dark to light theme
		html.removeAttribute("data-theme"); // No attribute = light theme
		localStorage.setItem("theme", "light");
	} else {
		// Switch from light to dark theme
		html.setAttribute("data-theme", "dark");
		localStorage.setItem("theme", "dark");
	}
	// END USER CODE
}
