// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
document.addEventListener("DOMContentLoaded", function() {
	const theme = localStorage.getItem("theme");
	if (theme === "dark") {
		document.documentElement.setAttribute("data-theme", "dark");
	}
});
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function ToggleTheme() {
	// BEGIN USER CODE
	const html = document.documentElement;
	const current = html.getAttribute("data-theme");
	if (current === "dark") {
		html.removeAttribute("data-theme");
		localStorage.setItem("theme", "light");
	} else {
		html.setAttribute("data-theme", "dark");
		localStorage.setItem("theme", "dark");
	}
	// END USER CODE
}
